/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.pkg01;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import projeto.pkg01.Classe_Principal.animal;


/**
 *
 * @author aluno
 */
public class Atendimento extends javax.swing.JFrame {

    
    
    /**
     * Creates new form Atendimento
     */
    public Atendimento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        botao2 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        botao3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox();
        form = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        altura = new javax.swing.JTextField();
        peso = new javax.swing.JTextField();
        especie = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tipo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cor = new javax.swing.JTextField();
        apelido = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        dtchegada = new javax.swing.JTextField();
        hrchegada = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        botao4 = new javax.swing.JButton();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenu4.setText("File");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem4.setText("Sair");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("File");

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem5.setText("Sair");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuBar2.add(jMenu5);

        botao2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botao2.setText("Voltar");
        botao2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });
        jTabbedPane2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPane2FocusGained(evt);
            }
        });
        jTabbedPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane2MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jPanel1CaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botao3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botao3.setText("Voltar");
        botao3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao3ActionPerformed(evt);
            }
        });
        jPanel1.add(botao3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 366, -1, -1));

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 0, 56)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Atendimento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 331, 78));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comboMousePressed(evt);
            }
        });
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        jPanel1.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 150, 235, -1));

        form.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        form.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        form.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formActionPerformed(evt);
            }
        });
        jPanel1.add(form, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 193, 309, 155));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Computadores");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 84, 331, -1));

        jTabbedPane2.addTab("Início", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Registro de Computadores");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 305, -1));

        altura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaActionPerformed(evt);
            }
        });
        jPanel3.add(altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 232, 95, -1));

        peso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoActionPerformed(evt);
            }
        });
        jPanel3.add(peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 232, 97, -1));

        especie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        especie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                especieActionPerformed(evt);
            }
        });
        jPanel3.add(especie, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 197, 237, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Altura:");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 231, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Espécie:");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 196, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Peso:");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 231, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Tipo:");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 161, -1, -1));

        tipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoActionPerformed(evt);
            }
        });
        jPanel3.add(tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 162, 260, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Data de Chegada:");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 92, -1, -1));

        id.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel3.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 58, 35, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Apelido:");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(84, 57, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("ID:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, -1, -1));

        cor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corActionPerformed(evt);
            }
        });
        jPanel3.add(cor, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 267, 268, -1));

        apelido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        apelido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apelidoActionPerformed(evt);
            }
        });
        jPanel3.add(apelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 58, 163, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Cor:");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 266, -1, -1));

        dtchegada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dtchegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtchegadaActionPerformed(evt);
            }
        });
        jPanel3.add(dtchegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 92, 160, -1));

        hrchegada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hrchegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrchegadaActionPerformed(evt);
            }
        });
        jPanel3.add(hrchegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 127, 159, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Hora de Chegada:");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 126, -1, -1));

        botao4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        botao4.setText("Registrar");
        botao4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao4ActionPerformed(evt);
            }
        });
        jPanel3.add(botao4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 480));

        jTabbedPane2.addTab("Registro de Computadores", jPanel2);

        jMenuBar4.setBackground(new java.awt.Color(239, 238, 236));
        jMenuBar4.setForeground(new java.awt.Color(102, 51, 0));

        jMenu7.setText("Opções");

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem7.setText("Sair");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem7);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItem2.setText("Atualizar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem2);

        jMenuBar4.add(jMenu7);

        setJMenuBar(jMenuBar4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Inicial");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void botao2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao2ActionPerformed
        Login frame = new Login();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_botao2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
Sair frame = new Sair();
frame.setVisible(true);
dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Atendimento frame = new Atendimento();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void botao3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao3ActionPerformed
        Login frame = new Login();
        frame.setVisible(true);
        dispose();
    }//GEN-LAST:event_botao3ActionPerformed

    private void hrchegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrchegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hrchegadaActionPerformed

    private void dtchegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtchegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtchegadaActionPerformed

    private void apelidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apelidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_apelidoActionPerformed

    private void corActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_corActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void botao4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao4ActionPerformed
// As linhas abaixo servem para a checagem de campos, se um ou mais campos não estiver preenchido(s), o programa retornará uma mensagem informando o usuário.
        if (id.getText()==null||id.getText().trim().equals("")) JOptionPane.showMessageDialog(null,"Campo ID não preenchido.");
        if (apelido.getText()==null||apelido.getText().trim().equals("")) JOptionPane.showMessageDialog(null,"Campo apelido não preenchido.");
        if (dtchegada.getText()==null||dtchegada.getText().trim().equals("")) JOptionPane.showMessageDialog(null,"Campo data não preenchido.");
        if (hrchegada.getText()==null||hrchegada.getText().trim().equals("")) JOptionPane.showMessageDialog(null,"Campo hora não preenchido.");
        if (tipo.getText()==null||tipo.getText().trim().equals("")) JOptionPane.showMessageDialog(null,"Campo tipo não preenchido.");
        if (peso.getText()==null||peso.getText().trim().equals("")) JOptionPane.showMessageDialog(null,"Campo peso não preenchido.");
        if (especie.getText()==null||especie.getText().trim().equals("")) JOptionPane.showMessageDialog(null,"Campo espécie não preenchido.");
        if (altura.getText()==null||altura.getText().trim().equals("")) JOptionPane.showMessageDialog(null,"Campo altura não preenchido.");
        if (cor.getText()==null||cor.getText().trim().equals("")) JOptionPane.showMessageDialog(null,"Campo cor não preenchido.");

        // As linhas abaixo servem também para a checagem de campos, o programa verifica se algum está vazio, caso todos estejam preenchidos, ele executa o if.
        if (!id.getText().isEmpty()&&
            !apelido.getText().isEmpty()&&
            !dtchegada.getText().isEmpty()&&
            !hrchegada.getText().isEmpty()&&
            !peso.getText().isEmpty()&&
            !tipo.getText().isEmpty()&&
            !especie.getText().isEmpty()&&
            !altura.getText().isEmpty()&&
            !cor.getText().isEmpty()){
            try {
                //Registra JDBC driver
                Class.forName("com.mysql.jdbc.Driver");

                //Abrindo a conexão: ATENÇÃO OS DOIS PARÂMETROS VAZIOS("") SÃO USUÁRIO E SENHA, RESPECTIVAMENTE.
                Connection conn = DriverManager.getConnection("jdbc:mysql://10.67.48.3:3306/bd_bicho_alexandre?zeroDateTimeBehavior=convertToNull", "aluno", "etec@147");

                //Executa a query de inserção
                java.sql.Statement st = conn.createStatement();
                String sql = "INSERT INTO tb05_cadastroanimal(tb05_peso,tb05_IDAnimal,tb05_tipoanimal,tb05_especie,tb05_altura,tb05_apelido,tb05_corpredominante,tb05_flag_doacao,tb05_flag_identificacao,"
                + "tb05_dt_chegada)"
                + " VALUES('"+Double.parseDouble(this.peso.getText())+"', '"+Integer.parseInt(this.id.getText())+"', '"+this.tipo.getText()+"','"+this.especie.getText()+"', '"
                +Double.parseDouble(this.altura.getText())+"','"+this.apelido.getText()+"', '"+this.cor.getText()+
                "', '"+this.dtchegada.getText()+"')";
                String sql2 = "INSERT INTO tb04_atendimento(tb04_HoraChegada,tb04_DtChegada,tb04_IDAnimal) VALUES ('"+this.dtchegada.getText()+"','"+this.hrchegada.getText()+"','"+Integer.parseInt(this.id.getText())+"')";
                st.executeUpdate(sql);
                st.executeUpdate(sql2);
                JOptionPane.showMessageDialog(null, "Registro efetuado com sucesso.");
                Atendimento frame = new Atendimento();
                frame.setVisible(true);
                dispose();
            } catch (SQLException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, e);
                Atendimento frame = new Atendimento();
                frame.setVisible(true);
                dispose();
            }//Fim try        // TODO add your handling code here:
        }
    }//GEN-LAST:event_botao4ActionPerformed

    private void tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoActionPerformed

    private void especieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_especieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_especieActionPerformed

    private void pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoActionPerformed

    private void alturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alturaActionPerformed

    private void comboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMouseClicked

    }//GEN-LAST:event_comboMouseClicked

    private void comboMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMousePressed

    }//GEN-LAST:event_comboMousePressed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        animal i = (animal) combo.getSelectedItem();
        form.setText("Id: "+i.id+"    Apelido: "+i.apelido+"    Tipo: "+i.tipo+"\n\nEspecie: "+i.especie+"    Cor: "+i.cor+"\n\nPeso: "+i.peso+"    Altura: "+i.altura+"\n\nData de Chegada: "+i.dtchegada);
    }//GEN-LAST:event_comboActionPerformed

    private void formActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://10.67.48.3:3306/bd_bicho_alexandre?zeroDateTimeBehavior=convertToNull", "aluno", "etec@147");
            String sql = "select * from tb05_cadastroanimal";
            PreparedStatement executa= conn.prepareStatement(sql);
            ResultSet rs = executa.executeQuery(sql);
            while(rs.next()){
            String id1=rs.getString(1); // 
            String apelido1=rs.getString(2);
            String dtchegada1=rs.getString(3);
            String tipo1=rs.getString(4);
            String peso1=rs.getString(5);//  
            String especie1=rs.getString(6);
            String altura1=rs.getString(7);
            String cor1=rs.getString(8);
                
            combo.addItem(new Classe_Principal.animal(id1,apelido1,dtchegada1,tipo1,peso1,especie1,altura1,cor1));  }
       
     }
            catch (SQLException | ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null,"Erro!");
            }    }//GEN-LAST:event_formWindowOpened

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
    }//GEN-LAST:event_jTabbedPane2StateChanged

    private void jPanel1CaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jPanel1CaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1CaretPositionChanged

    private void jTabbedPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane2MouseClicked
    }//GEN-LAST:event_jTabbedPane2MouseClicked

    private void jTabbedPane2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPane2FocusGained
    }//GEN-LAST:event_jTabbedPane2FocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Atendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Atendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Atendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Atendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Atendimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField altura;
    private javax.swing.JTextField apelido;
    private javax.swing.JButton botao2;
    private javax.swing.JButton botao3;
    private javax.swing.JButton botao4;
    private javax.swing.JComboBox combo;
    private javax.swing.JTextField cor;
    private javax.swing.JTextField dtchegada;
    private javax.swing.JTextField especie;
    private javax.swing.JFormattedTextField form;
    private javax.swing.JTextField hrchegada;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField peso;
    private javax.swing.JTextField tipo;
    // End of variables declaration//GEN-END:variables
}
